### ISSUE TITLE
Generation fails with error "TypeError [ERR_INVALID_CALLBACK]: Callback must be a function"

### ISSUE THREAD

**Issue by ColinEberhardt** [trodi/blockly-d.ts#8]
```
$ npm i

$ npm start

> blockly-d.ts@0.0.0 start /Users/colineberhardt/Temp/blockly-d.ts
> bash npm-scripts/generate.sh

Cloning into 'blockly'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 27979 (delta 4), reused 6 (delta 2), pack-reused 27958
Receiving objects: 100% (27979/27979), 72.14 MiB | 4.52 MiB/s, done.
Resolving deltas: 100% (21758/21758), done.
ERROR	blockly/core/block.js block.d.ts
/Users/colineberhardt/Temp/blockly-d.ts/node_modules/typescript-closure-tools/definition-generator/src/main.js:33
        throw e;
        ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1132:14)
    at /Users/colineberhardt/Temp/blockly-d.ts/node_modules/typescript-closure-tools/definition-generator/src/main.js:27:16
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/colineberhardt/Temp/blockly-d.ts/node_modules/typescript-closure-tools/definition-generator/src/main.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
mv: rename *.d.ts to output/*.d.ts: No such file or directory
cat: output/*.d.ts: No such file or directory
mkdir: ../dist/: File exists
Colins-MacBook-Pro:blockly-d.ts colineberhardt$ 
```

**Comment by trodi** [comment]
@ColinEberhardt I suspect you are running Node v10? It appears that Node has started throwing errors in use cases it didn't before. Give Node 8.x a try. I'll look into making a PR to fix our underlying dependency.

**Details**
I tested cloning/running on both win7 and macOS boxes running on Node v8.11.4. In both cases the script ran correctly to completion with the expected files `dist/`. It does appear that newer versions of node now throw deprecations warnings though.

The error you see is being thrown when `typescript-closure-tools` dependency is calling fs.writeFile. That lib doesn't provide `fs` with a callback function and this **_now_** appears to be a use case where Node throws an error.

**Comment by ColinEberhardt** [comment]
Thanks @trodi - I tried v8.6 and generation worked

**Comment by trodi** [comment]
@ColinEberhardt node v10 is now supported.

**Comment by ColinEberhardt** [comment]
Thanks for the heads-up @trodi
